DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE tank (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  tankname TEXT NOT NULL,
  tankimg TEXT NOT NULL,
  tankdescription TEXT NOT NULL,

  tankfrontalarmor INTEGER NOT NULL,
  tanksidearmor INTEGER NOT NULL,

  tankcannon INTEGER NOT NULL,

  tankengine INTEGER NOT NULL,

  FOREIGN KEY (owner_id) REFERENCES user (id)
);